print("--- list operation ---")
print("\ncreation of list")
my_list=['a','b','c','d']
print("my list:",my_list)
print("\nappend(): adds an element at the last position.")
my_list.append('e')
print("appended list:",my_list)
print("\ncopy(): copies one list to another variable.")
c=my_list.copy()
print("copied list:",c)
print("\nclear(): removes all elements from the copied list.")
c.clear()
print("cleared list:",c)
print("\ncount(): counts how many times an element is repeated.")
co=my_list.count('d')
print("count of 'd':",co)
print("\nextend(): adds multiple elements to the list at the end.")
my_list.extend(['g','f'])
print("extended list:",my_list)
print("\nindex(): returns the index of a specific element.")
i=my_list.index('g')
print("index of 'g':",i)
print("\ninsert(): inserts an element at a specific position.")
my_list.insert(0,'1')
print("insert 0 index 1 element:",my_list)
print("\npop(): removes the element from given index and returns it (here index 0).")
p=my_list.pop(0)
print("pop:",p)
print("\nremove(): removes a specific element.")
my_list.remove('g')
print("removed element:",my_list)
print("\nreverse(): reverses the list.")
my_list.reverse()
print("reversed list:",my_list)
print("\nsort(): arranges elements in ascending order.")
my_list.sort()
print("sorted list:",my_list)